---
- name: Build hostsfile entry list dynamically
  ansible.builtin.set_fact:
    hostsfile_dynamic_hosts_entries: >-
      {{ groups['all'] | map('extract', hostvars) | list | json_query('[].{ip: ansible_host, name: inventory_hostname}') | list }}

- name: Manage /etc/hosts entries (dynamic)
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ item.ip }}\\s+{{ item.name }}"
    line: "{{ item.ip }} {{ item.name }}"
    state: present
  loop: "{{ hostsfile_dynamic_hosts_entries | default([]) }}"
