---
# Master playbook orchestrating configuration

- name: Common base config (all hosts)
  hosts: all
  become: true
  roles:
    - ssh_hardening
    - hostsfile
    - firewalld
    - { role: chrony, when: "'ntp' not in group_names" }
    - rhel_client

- name: NTP server configuration
  hosts: ntp
  become: true
  roles:
    - ntpd

- name: Web server configuration
  hosts: web
  become: true
  roles:
    - httpd

- name: Database server configuration
  hosts: db
  become: true
  roles:
    - postgresql
